start chrome.exe https://realpython.com/courses/binary-bytes-bitwise-operators/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-pretty-print/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-advent-of-code/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/data-viz-with-dash/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/build-neural-network-python-ai/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/interview-eric-wastl/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-news-october-2021/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/building-lists-with-python-append/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/django-nginx-gunicorn/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/advanced-visual-studio-code-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/using-pltscatter-visualize-data-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-typer-cli/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/build-a-content-aggregator-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/reading-input-writing-output-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-zipapp/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/django-template-custom-tags-filters/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/writing-idiomatic-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-not-operator/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/len-python-function/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/python-assignment-expressions-walrus-operator/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-xml-parser/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-property/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/asteroids-game-python-pygame/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-fractions/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-sum-function/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/cool-new-features-python-310/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python310-new-features/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/django-hosting-on-heroku/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/python-rock-paper-scissors-game/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/reverse-string-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/django-templates-tags-filters/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/pass-by-reference-python-best-practices/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-and-operator/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/django-diary-project-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/python-data-classes/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-news-august-2021/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/fibonacci-sequence-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/graph-data-with-python-and-ggplot/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/how-long-does-it-take-to-learn-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/splitting-datasets-scikit-learn-train-test-split/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-optional-arguments/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/exploring-python-math-module/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-deque/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/reading-writing-files-pandas/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-news-july-2021/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/effective-python-return-statement/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-walrus-operator/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/python-sleep-uptime-bot/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-chainmap/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/api-integration-in-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/pandas-dataframe-working-with-data/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-collections-module/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/django-setup/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/speech-recognition-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/interview-dustin-ingram/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/fastapi-python-web-apis/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/square-root-function-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-news-june-2021/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/what-can-i-do-with-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/defining-and-calling-functions/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-counter/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/beautiful-soup-web-scraper-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/python-inner-functions/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-reverse-list/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/cpython-internals-paperback/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/python-vs-javascript-for-python-devs/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-complex-numbers/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-scipy-linalg/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/gradebook-using-pandas-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-interview-problem-parsing-csv-files/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-filter-function/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/setting-up-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/interview-sebastian-ramirez/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-with-statement/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/explore-dataset-with-pandas/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-news-may-2021/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/visualizing-python-plt-scatter/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/set-up-django-project/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-django-blog/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/bulk-file-rename-tool-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/using-python-or-operator/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/embedded-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-namedtuple/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/stacks-queues-ideal-data-structure/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-recursion/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/nltk-nlp-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/simplify-gui-dev-pysimplegui/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-news-april-2021/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/platformer-python-arcade/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/map-function-transform-iterables/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-basics-paperback/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/interview-moshe-zadka/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/text-classification-with-keras/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/flask-by-example-part-1-project-setup/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/directory-tree-generator-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/start-with-pyenv/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/start-contributing-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/knn-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/python-vs-java-object-oriented-programming/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-news-march-2021/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/interview-will-mcgugan/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/understand-list-comprehensions/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-ordereddict/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/interview-dane-hillard/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/records-sets-ideal-data-structure/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/asteroids-game-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-ai-neural-network/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/booleans-leveraging-truth/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/interview-ewa-jodlowska/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-contact-book/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/django-view-authorization/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/real-python-podcast-first-year/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/article-bookmarks-search-improvements/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/navigate-namespaces-scope/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/introduction-to-mongodb-and-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/brython-python-in-browser/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/dicts-arrays-ideal-data-structure/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-api/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-functional-programming/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/creating-pyqt-layouts-gui-applications/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/pandas-sort-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-microservices-grpc/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/python-modulo-operator/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/inner-functions-what-are-they-good-for/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/qt-designer-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/plot-pandas-data-visualization/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-web-applications/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/gradient-descent-algorithm-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/evaluate-expressions-dynamically-python-eval/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-first-steps/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/c-for-python-programmers/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/intro-sorting-algorithms/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-rock-paper-scissors/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-nltk-sentiment-analysis/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/managing-python-dependencies/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/numpy-tutorial/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-dash/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/django-rest-framework/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-append/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/django-admin-customization/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-mysql/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/pickle-serializing-objects/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-pyqt-qthread/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-pass/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/python-turtle-beginners/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-data-engineer/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-bitwise-operators/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/speed-python-concurrency/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/office-hours-announcement/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-pyqt-database/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/how-python-manages-memory/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/np-linspace-numpy/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-pyqt-layout/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/formatting-python-strings/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/train-test-split-python-data/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-enumerate/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/building-regexes-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-menus-toolbars/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/pypy-faster-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/python-defaultdict-type/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/sentiment-analysis-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/lru-cache-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/simulating-processes-simpy/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-scipy-fft/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/django-view-authorization/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/creating-binary-search-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-modulo-operator/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/community-slack-guide/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/getting-started-micropython/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-boolean/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-sqlite-sqlalchemy/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/web-scraping-beautiful-soup/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/ggplot-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/interview-anthony-shaw/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/cool-new-features-python-39/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python39-new-features/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-map-function/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/using-google-login-flask/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-return-statement/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/interview-david-amos/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/working-linked-lists-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-practice-problems/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-numbers/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/command-line-interfaces/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/pandas-plot-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-debug-idle/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/exploring-https-cryptography/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/video-subtitles-transcripts-now-available/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/pytorch-vs-tensorflow/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/editing-excel-python-openpyxl/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/installing-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-data-structures/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/django-redirects/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-mmap/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-data-version-control/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/office-hours/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-web-scraping-practical-introduction/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/interview-bruno-oliveira/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/identify-invalid-syntax/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-pass-by-reference/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-wheels/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/practical-recipes-files/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/customize-django-admin-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-namespaces-scope/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/python-none/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/generative-adversarial-networks/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-packages/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/mastering-time-module/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/k-means-clustering-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/pandas-project-gradebook/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/intermediate-project-ideas/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-ipaddress-module/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-import/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/pointers-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python3-object-oriented-programming/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/django-user-management/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/python-unicode/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-reduce-function/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-heapq-module/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/discord-bot-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/linear-programming-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/pysimplegui-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/python-generators/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-keywords/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/pandas-settingwithcopywarning/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/python-traceback/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/interview-kattni-rembor/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/regex-python-part-2/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/python-zip-function/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-raspberry-pi/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/installable-django-app/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/what-is-pip/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/creating-modifying-pdf/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/interview-russell-keith-magee/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/convert-python-string-int/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-vs-javascript/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/interview-christopher-bailey/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/python-mock-object-library/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-eval-function/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/move-django-model/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/python-print/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-datetime/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/regex-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/structuring-python-application/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-pickle-module/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/pandas-dataframe/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/python-coding-interviews-tips-best-practices/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/pytest-python-testing/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/sorting-algorithms-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/inheritance-composition-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/pandas-merge-join-and-concat/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/django-pytest-fixtures/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/arduino-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/instagram-bot-python-instapy/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/linked-lists-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/python-is-identity-vs-equality/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/any-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/simpy-simulating-with-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/numpy-arange/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-math-module/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/real-python-podcast-launch/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-scope-legb-rule/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/pygame-primer/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/binary-search-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-defaultdict/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/python-main-function/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/defining-your-own-python-function/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/alexa-python-skill/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/python-stack/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-bindings-overview/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/beginners-guide-python-turtle/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/pdf-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-sql-libraries/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/null-in-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/finding-perfect-python-code-editor/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-formatted-output/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/interview-brett-slatkin/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/playing-and-recording-sound-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-interface/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-command-line-arguments/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/sets-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/flask-blueprint/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-is-identity-vs-equality/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/python-modules-packages/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-community-interview-kelly-and-sean-teaching-python/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-gui-tkinter/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/courses/python-data-types/ 
TIMEOUT /T 5
start chrome.exe https://realpython.com/python-scipy-cluster-optimize/ 
TIMEOUT /T 5