import functions


# this module give us the ability to automate selenium with just 5 params
#
# the list should have 4 params [url,css_selector,sleeping_time,javascript_to_execute,result_saving_file]
#
# element sould be in the list =======
# url = x[0]
# css_selector = x[1]
# sleep_timer = x[2]
# javascript = x[3]
# saving_file = x[4]
# ====================================
# functions.selenium  (
#     [["http://www.youtube.com" ,
#      "*" ,
#      3,
#     "document.body.innerHTML = ''",
#      "./selenium_result/output.txt"]
#      ,
#      ["http://www.kooora.com" ,
#       "*" ,
#       0,
#       "",
#      "./selenium_result/output.txt"],

#     ]
# )

# params = functions.get_cli_arguments()
# print(params)
# functions .selenium([params])


# functions.selenium (

# [
# ["https://www.javatpoint.com/python-tutorial ","*",1,"document.body.innerText = document.body.innerHTML","./selenium_result/javatopoint_python_pdf"],
# ]
# )

# functions.selenium(
#     [
#         ["https://www.w3schools.com/python/python_ref_functions.asp", "*", 1,
#            " document.body.innerText = document.querySelector('#main').innerHTML", "./selenium_result/w3schools_python_reference.html"],
#         ["https://www.w3schools.com/python/python_ref_string.asp", "*", 1,
#            " document.body.innerText = document.querySelector('#main').innerHTML", "./selenium_result/w3schools_python_reference.html"],
#         ["https://www.w3schools.com/python/python_ref_list.asp", "*", 1,
#            " document.body.innerText = document.querySelector('#main').innerHTML", "./selenium_result/w3schools_python_reference.html"],
#         ["https://www.w3schools.com/python/python_ref_dictionary.asp", "*", 1,
#            " document.body.innerText = document.querySelector('#main').innerHTML", "./selenium_result/w3schools_python_reference.html"],
#         ["https://www.w3schools.com/python/python_ref_tuple.asp", "*", 1,
#            " document.body.innerText = document.querySelector('#main').innerHTML", "./selenium_result/w3schools_python_reference.html"],
#         ["https://www.w3schools.com/python/python_ref_set.asp", "*", 1,
#            " document.body.innerText = document.querySelector('#main').innerHTML", "./selenium_result/w3schools_python_reference.html"],
#         ["https://www.w3schools.com/python/python_ref_file.asp", "*", 1,
#            " document.body.innerText = document.querySelector('#main').innerHTML", "./selenium_result/w3schools_python_reference.html"],
#         ["https://www.w3schools.com/python/python_ref_keywords.asp", "*", 1,
#            " document.body.innerText = document.querySelector('#main').innerHTML", "./selenium_result/w3schools_python_reference.html"],
#         ["https://www.w3schools.com/python/python_ref_exceptions.asp", "*", 1,
#            " document.body.innerText = document.querySelector('#main').innerHTML", "./selenium_result/w3schools_python_reference.html"],
#         ["https://www.w3schools.com/python/python_ref_glossary.asp", "*", 1,
#            " document.body.innerText = document.querySelector('#main').innerHTML", "./selenium_result/w3schools_python_reference.html"],
#         ["https://www.w3schools.com/python/module_random.asp", "*", 1,
#            " document.body.innerText = document.querySelector('#main').innerHTML", "./selenium_result/w3schools_python_reference.html"],
#         ["https://www.w3schools.com/python/module_requests.asp", "*", 1,
#            " document.body.innerText = document.querySelector('#main').innerHTML", "./selenium_result/w3schools_python_reference.html"],
#         ["https://www.w3schools.com/python/module_math.asp", "*", 1,
#            " document.body.innerText = document.querySelector('#main').innerHTML", "./selenium_result/w3schools_python_reference.html"],
#         ["https://www.w3schools.com/python/module_cmath.asp", "*", 1,
#            " document.body.innerText = document.querySelector('#main').innerHTML", "./selenium_result/w3schools_python_reference.html"],
#     ]
# )


functions.selenium(

 [["https://overapi.com/firebug","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\firebug.html"], 
["https://overapi.com/firefox","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\firefox.html"], 
["https://overapi.com/firefox-add-ons","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\firefox.html"], 
["https://overapi.com/fitnesse","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\fitnesse.html"], 
["https://overapi.com/flash","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\flash.html"], 
["https://overapi.com/flash-catalyst","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\flash.html"], 
["https://overapi.com/flex","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\flex.html"], 
["https://overapi.com/fonts","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\fonts.html"], 
["https://overapi.com/fortran","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\fortran.html"], 
["https://overapi.com/freeware","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\freeware.html"], 
["https://overapi.com/ftp","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\ftp.html"], 
["https://overapi.com/first-hop-redundancy","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\first.html"], 
["https://overapi.com/gdb","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\gdb.html"], 
["https://overapi.com/geometry","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\geometry.html"], 
["https://overapi.com/gift","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\gift.html"], 
["https://overapi.com/gimp","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\gimp.html"], 
["https://overapi.com/git","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\git.html"], 
["https://overapi.com/glassfish","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\glassfish.html"], 
["https://overapi.com/gmail","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\gmail.html"], 
["https://overapi.com/design-pattern","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\design.html"], 
["https://overapi.com/google","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\google.html"], 
["https://overapi.com/google-chrome","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\google.html"], 
["https://overapi.com/google-maps","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\google.html"], 
["https://overapi.com/google-app-engine","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\google.html"], 
["https://overapi.com/grails","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\grails.html"], 
["https://overapi.com/griffon","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\griffon.html"], 
["https://overapi.com/groovy","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\groovy.html"], 
["https://overapi.com/guitar","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\guitar.html"], 
["https://overapi.com/gwt","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\gwt.html"], 
["https://overapi.com/hardware","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\hardware.html"], 
["https://overapi.com/hadoop","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\hadoop.html"], 
["https://overapi.com/haskell","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\haskell.html"], 
["https://overapi.com/hbase","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\hbase.html"], 
["https://overapi.com/hibernate","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\hibernate.html"], 
["https://overapi.com/scalability","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\scalability.html"], 
["https://overapi.com/htaccess","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\htaccess.html"], 
["https://overapi.com/html","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\html.html"], 
["https://overapi.com/http","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\http.html"], 
["https://overapi.com//ivomynttinen.com/blog/the-ios-7-design-cheat-sheet","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\/ivomynttinen.html"], 
["https://overapi.com/icons","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\icons.html"], 
["https://overapi.com/illustrator","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\illustrator.html"], 
["https://overapi.com/intellij-idea","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\intellij.html"], 
["https://overapi.com/ie","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\ie.html"], 
["https://overapi.com/irc","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\irc.html"], 
["https://overapi.com/ivr","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\ivr.html"], 
["https://overapi.com/ieee80211","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\ieee80211.html"], 
["https://overapi.com/ieee8021x","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\ieee8021x.html"], 
["https://overapi.com/ipsec","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\ipsec.html"], 
["https://overapi.com/ipv4","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\ipv4.html"], 
["https://overapi.com/ipv6","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\ipv6.html"], 
["https://overapi.com/is-is","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\is.html"], 
["https://overapi.com/java","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\java.html"], 
["https://overapi.com/javaee","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\javaee.html"], 
["https://overapi.com/jpa","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\jpa.html"], 
["https://overapi.com/javafx","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\javafx.html"], 
["https://overapi.com/javascript","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\javascript.html"], 
["https://overapi.com/jsf","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\jsf.html"], 
["https://overapi.com/jboss","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\jboss.html"], 
["https://overapi.com/jdbc","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\jdbc.html"], 
["https://overapi.com/jetty","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\jetty.html"], 
["https://overapi.com/jquery","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\jquery.html"], 
["https://overapi.com/jsf","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\jsf.html"], 
["https://overapi.com/jsp","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\jsp.html"], 
["https://overapi.com/junit","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\junit.html"], 
["https://overapi.com/languages","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\languages.html"], 
["https://overapi.com/latex","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\latex.html"], 
["https://overapi.com/latex-suite","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\latex.html"], 
["https://overapi.com/less","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\less.html"], 
["https://overapi.com/linux","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\linux.html"], 
["https://overapi.com/lisp","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\lisp.html"], 
["https://overapi.com/logic","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\logic.html"], 
["https://overapi.com/lotus-domino","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\lotus.html"], 
["https://overapi.com/lua","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\lua.html"], 
["https://overapi.com/lucene","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\lucene.html"], 
["https://overapi.com/mac","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\mac.html"], 
["https://overapi.com/osx","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\osx.html"], 
["https://overapi.com/machine-learning","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\machine.html"], 
["https://overapi.com/maple","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\maple.html"], 
["https://overapi.com/markdown","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\markdown.html"], 
["https://overapi.com/math","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\math.html"], 
["https://overapi.com/mathematica","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\mathematica.html"], 
["https://overapi.com/mathml","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\mathml.html"], 
["https://overapi.com/mathomatic","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\mathomatic.html"], 
["https://overapi.com/matlab","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\matlab.html"], 
["https://overapi.com/maven","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\maven.html"], 
["https://overapi.com/maxima","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\maxima.html"], 
["https://overapi.com/mfc","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\mfc.html"], 
["https://overapi.com/microformats","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\microformats.html"], 
["https://overapi.com/microsoft-excel","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\microsoft.html"], 
["https://overapi.com/msp","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\msp.html"], 
["https://overapi.com/microsoft-visual-studio","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\microsoft.html"], 
["https://overapi.com/mime","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\mime.html"], 
["https://overapi.com/ssi","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\ssi.html"], 
["https://overapi.com/mod_perl","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\mod_perl.html"], 
["https://overapi.com/mod_rewrite","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\mod_rewrite.html"], 
["https://overapi.com/mongo-shell","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\mongo.html"], 
["https://overapi.com/mootools","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\mootools.html"], 
["https://overapi.com/msp","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\msp.html"], 
["https://overapi.com/mule","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\mule.html"], 
["https://overapi.com/music","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\music.html"], 
["https://overapi.com/mvvm","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\mvvm.html"], 
["https://overapi.com/mysql","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\mysql.html"], 
["https://overapi.com/mediawiki","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\mediawiki.html"], 
["https://overapi.com/netbeans","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\netbeans.html"], 
["https://overapi.com/nmap","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\nmap.html"], 
["https://overapi.com/nodejs","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\nodejs.html"], 
["https://overapi.com/numbers","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\numbers.html"], 
["https://overapi.com/objective-c","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\objective.html"], 
["https://overapi.com/ocaml","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\ocaml.html"], 
["https://overapi.com/osmf","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\osmf.html"], 
["https://overapi.com/opencl","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\opencl.html"], 
["https://overapi.com/opencv","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\opencv.html"], 
["https://overapi.com/openmp","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\openmp.html"], 
["https://overapi.com/opensearch","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\opensearch.html"], 
["https://overapi.com/openssh","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\openssh.html"], 
["https://overapi.com/openvz","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\openvz.html"], 
["https://overapi.com/oracle","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\oracle.html"], 
["https://overapi.com/org-mode","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\org.html"], 
["https://overapi.com/osx","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\osx.html"], 
["https://overapi.com/ospf","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\ospf.html"], 
["https://overapi.com/perforce","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\perforce.html"], 
["https://overapi.com/perl","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\perl.html"], 
["https://overapi.com/photoshop","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\photoshop.html"], 
["https://overapi.com/php","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\php.html"], 
["https://overapi.com/php-frameworks","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\php.html"], 
["https://overapi.com/physics","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\physics.html"], 
["https://overapi.com/play-framework","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\play.html"], 
["https://overapi.com/postgresql","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\postgresql.html"], 
["https://overapi.com/windows-powershell","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\windows.html"], 
["https://overapi.com/probability-theory","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\probability.html"], 
["https://overapi.com/processing","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\processing.html"], 
["https://overapi.com/prototype","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\prototype.html"], 
["https://overapi.com/python","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\python.html"], 
["https://overapi.com/ppp","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\ppp.html"], 
["https://overapi.com/ports","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\ports.html"], 
["https://overapi.com/phpstorm","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\phpstorm.html"], 
["https://overapi.com/qt","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\qt.html"], 
["https://overapi.com/quicksilver","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\quicksilver.html"], 
["https://overapi.com/r","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\r.html"], 
["https://overapi.com/redhat","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\redhat.html"], 
["https://overapi.com/regex","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\regex.html"], 
["https://overapi.com/religion","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\religion.html"], 
["https://overapi.com/rest","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\rest.html"], 
["https://overapi.com/richfaces","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\richfaces.html"], 
["https://overapi.com/rip","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\rip.html"], 
["https://overapi.com/rpm","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\rpm.html"], 
["https://overapi.com/atom","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\atom.html"], 
["https://overapi.com/ruby","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\ruby.html"], 
["https://overapi.com/rubyrails","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\rubyrails.html"], 
["https://overapi.com/rust","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\rust.html"], 
["https://overapi.com/sandcastle","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\sandcastle.html"], 
["https://overapi.com/scala","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\scala.html"], 
["https://overapi.com/scalability","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\scalability.html"], 
["https://overapi.com/science","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\science.html"], 
["https://overapi.com/screen","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\screen.html"], 
["https://overapi.com/seam","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\seam.html"], 
["https://overapi.com/sed","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\sed.html"], 
["https://overapi.com/selenium","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\selenium.html"], 
["https://overapi.com/sendmail","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\sendmail.html"], 
["https://overapi.com/servicemix","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\servicemix.html"], 
["https://overapi.com/shellscript","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\shellscript.html"], 
["https://overapi.com/silverlight","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\silverlight.html"], 
["https://overapi.com/smile","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\smile.html"], 
["https://overapi.com/social-bookmarks","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\social.html"], 
["https://overapi.com/solaris","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\solaris.html"], 
["https://overapi.com/spring","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\spring.html"], 
["https://overapi.com/springroo","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\springroo.html"], 
["https://overapi.com/sql","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\sql.html"], 
["https://overapi.com/sqlserver","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\sqlserver.html"], 
["https://overapi.com/sqlite","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\sqlite.html"], 
["https://overapi.com/ssi","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\ssi.html"], 
["https://overapi.com/tls","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\tls.html"], 
["https://overapi.com/statistics","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\statistics.html"], 
["https://overapi.com/svg","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\svg.html"], 
["https://overapi.com/svn","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\svn.html"], 
["https://overapi.com/sybase","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\sybase.html"], 
["https://overapi.com/symfony","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\symfony.html"], 
["https://overapi.com/symfony2","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\symfony2.html"], 
["https://overapi.com/spanning-tree","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\spanning.html"], 
["https://overapi.com/scapy","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\scapy.html"], 
["https://overapi.com/tapestry","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\tapestry.html"], 
["https://overapi.com/tcltk","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\tcltk.html"], 
["https://overapi.com/tcp","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\tcp.html"], 
["https://overapi.com/tex","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\tex.html"], 
["https://overapi.com/thunderbird","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\thunderbird.html"], 
["https://overapi.com/tlds","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\tlds.html"], 
["https://overapi.com/tls","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\tls.html"], 
["https://overapi.com/trigonometry","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\trigonometry.html"], 
["https://overapi.com/ttcn-3","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\ttcn.html"], 
["https://overapi.com/twitter","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\twitter.html"], 
["https://overapi.com/tcpdump","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\tcpdump.html"], 
["https://overapi.com/uml","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\uml.html"], 
["https://overapi.com/ubuntu","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\ubuntu.html"], 
["https://overapi.com/unicode","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\unicode.html"], 
["https://overapi.com/unix","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\unix.html"], 
["https://overapi.com/unicode","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\unicode.html"], 
["https://overapi.com/underscorejs","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\underscorejs.html"], 
["https://overapi.com/vaadin","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\vaadin.html"], 
["https://overapi.com/visualbasic","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\visualbasic.html"], 
["https://overapi.com/microsoft-excel","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\microsoft.html"], 
["https://overapi.com/vbscript","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\vbscript.html"], 
["https://overapi.com/vcs","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\vcs.html"], 
["https://overapi.com/vi","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\vi.html"], 
["https://overapi.com/vim","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\vim.html"], 
["https://overapi.com/latex-suite","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\latex.html"], 
["https://overapi.com/virtualization","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\virtualization.html"], 
["https://overapi.com/visualbasic","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\visualbasic.html"], 
["https://overapi.com/vmware","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\vmware.html"], 
["https://overapi.com/voicexml","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\voicexml.html"], 
["https://overapi.com/vvvv","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\vvvv.html"], 
["https://overapi.com/webgl","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\webgl.html"], 
["https://overapi.com/webmatrix","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\webmatrix.html"], 
["https://overapi.com/wicket","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\wicket.html"], 
["https://overapi.com/wikipedia","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\wikipedia.html"], 
["https://overapi.com/windows","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\windows.html"], 
["https://overapi.com/azure","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\azure.html"], 
["https://overapi.com/wcf","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\wcf.html"], 
["https://overapi.com/wpf","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\wpf.html"], 
["https://overapi.com/windows-powershell","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\windows.html"], 
["https://overapi.com/wordpress","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\wordpress.html"], 
["https://overapi.com/wow","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\wow.html"], 
["https://overapi.com/bpel","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\bpel.html"], 
["https://overapi.com/wireshark-display-filters","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\wireshark.html"], 
["https://overapi.com/xhtml","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\xhtml.html"], 
["https://overapi.com/xml","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\xml.html"], 
["https://overapi.com/xml-schema","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\xml.html"], 
["https://overapi.com/xpath","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\xpath.html"], 
["https://overapi.com/xsl","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\xsl.html"], 
["https://overapi.com/xslt","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\xslt.html"], 
["https://overapi.com/xss","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\xss.html"], 
["https://overapi.com/yahoo","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\yahoo.html"], 
["https://overapi.com/emmet","*", 0,"document.body.innerText = document.documentElement.innerHTML ", r"C:\Users\smart hp1\Downloads\cheatseet\emmet.html"], ]

     )
